Repository Team-KIN/Forest-Android, pull requests merged in 2023-12, with the labels that each got.

#4 🔀 :: (#1) login UI publishing
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kin/presentation/ui/auth/AuthActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/auth/component/EmailTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/auth/component/LoginButton.kt
  presentation/src/main/java/com/kin/presentation/ui/auth/component/OrSignUp.kt
  presentation/src/main/java/com/kin/presentation/ui/auth/component/PasswordTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/auth/component/Title.kt
  presentation/src/main/java/com/kin/presentation/ui/auth/screen/AuthScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/ColorTheme.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/color/LightColor.kt
  presentation/src/main/res/drawable/forest_title.xml
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#9 🔀 :: (#3) group list UI publishing
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/kin/presentation/ui/change_password/ChangePasswordActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/change_password/screen/ChangePasswordScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/component/back_page/BackPage.kt
  presentation/src/main/java/com/kin/presentation/ui/component/navigation/BottomNavItem.kt
  presentation/src/main/java/com/kin/presentation/ui/component/navigation/BottomNavigationBar.kt
  presentation/src/main/java/com/kin/presentation/ui/component/navigation/NavigationGraph.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/component/GroupList.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/component/GroupListTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/component/OptionButton.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/component/dialog/GroupPageDiaglog.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/item/GroupItemList.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/screen/GroupListScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/EmailTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/LoginButton.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/OrSignUp.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/PasswordTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/Title.kt
  presentation/src/main/java/com/kin/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/ColorTheme.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/color/LightColor.kt
  presentation/src/main/res/drawable/group_list_dialog.xml
  presentation/src/main/res/drawable/group_list_icon.xml
  presentation/src/main/res/drawable/member_icon.xml
  presentation/src/main/res/drawable/my_group_icon.xml
  presentation/src/main/res/drawable/my_page_icon.xml
  presentation/src/main/res/drawable/option_icon.xml
  presentation/src/main/res/drawable/search_icon.xml
  presentation/src/main/res/drawable/todo_icon.xml
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#13 🔀 :: (#5) create group UI publishing
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/CreateGroupTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/GroupNameTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/GroupStatus.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/GroupTargetTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/NextPageButton.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/screen/CreateGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/ColorTheme.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/color/LightColor.kt
  presentation/src/main/res/drawable/drop_down_icon.xml
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#15 🔀 :: (#7) join private group UI publishing
  presentation/src/main/java/com/kin/presentation/ui/join_private_group/component/InsertCodeTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/join_private_group/component/JoinButton.kt
  presentation/src/main/java/com/kin/presentation/ui/join_private_group/component/JoinPrivateGroupTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/join_private_group/screen/JoinPrivateGroupScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#18 🔀 : : (#8) modify text color
  presentation/src/main/java/com/kin/presentation/ui/change_password/component/ChangePasswordTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/component/back_page/BackPage.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/GroupStatus.kt
Labels: 2️⃣ Priortiy: Medium, 🎨 Type: Publishing

#21 🔀 :: (#10) new group description UI publishing
  presentation/src/main/java/com/kin/presentation/ui/create_group/component/CreateGroupTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/component/CreateGroupButton.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/component/DescriptionTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/component/GropuDescriptionTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/component/LatterNum.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/screen/NewGroupDescriptionScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#23 🔀 :: (#11) detail group UI publishing
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/component/GroupDescription.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/component/GroupMemberNum.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/component/GroupNameTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/component/GroupTarget.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/component/JoinGroupButton.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/screen/DetailGroupScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#25 🔀 :: (#12) group todo UI publishing
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/GroupName.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/TodoToggle.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/group_todo/GroupTodoCheck.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/group_todo/GroupTodoTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/group_todo/check_item/GroupCheckItem.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/private_todo/AddPrivateTodoTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/private_todo/PrivateTodoCheck.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/private_todo/PrivateTodoTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/private_todo/check_item/PrivateCheckItem.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/screen/GroupTodoScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/ColorTheme.kt
  presentation/src/main/java/com/kin/presentation/ui/theme/color/LightColor.kt
  presentation/src/main/res/drawable/add_todo_icon.xml
  presentation/src/main/res/drawable/check_icon.xml
  presentation/src/main/res/drawable/default_check_box_icon.xml
  presentation/src/main/res/drawable/notice_toggle.xml
  presentation/src/main/res/drawable/setting_icon.xml
  presentation/src/main/res/drawable/todo_toggle.xml
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#38 🔀 :: (#33) group setting page publishing
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/CodeCopyButton.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupDeleteButton.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupExplainTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupExplanEditButton.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupGoalEditButton.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupGoalTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupMemberEditButton.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupMemberList.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/component/GroupSettingTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/item/GroupMemberItem.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/screen/GroupSettingScreen.kt
  presentation/src/main/res/drawable/copy_code_icon.xml
  presentation/src/main/res/drawable/group_setting_edit_icon.xml
  presentation/src/main/res/drawable/member_setting_icon.xml
  presentation/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High

#42 🔀 :: (#39) signup logic
  app/src/main/java/com/kin/forest_android/module/NetworkModule.kt
  app/src/main/java/com/kin/forest_android/module/RemoteDataSourceModule.kt
  app/src/main/java/com/kin/forest_android/module/RepositoryModule.kt
  data/src/main/java/com/kin/data/remote/api/signup/SignupAPI.kt
  data/src/main/java/com/kin/data/remote/datasource/signup/SignupDataSource.kt
  data/src/main/java/com/kin/data/remote/datasource/signup/SignupDataSourceImpl.kt
  data/src/main/java/com/kin/data/remote/dto/signup/request/SignupRequest.kt
  data/src/main/java/com/kin/data/repository/SignupRepositoryImpl.kt
  domain/src/main/java/com/kin/domain/model/signup/request/SignupRequestModel.kt
  domain/src/main/java/com/kin/domain/repository/SignupRepository.kt
  domain/src/main/java/com/kin/domain/usecase/signup/SignupUseCase.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/SignUpActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/component/EmailTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/component/NicknameTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/component/PasswordCheckTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/component/PasswordTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/component/PhoneNumberTextFiled.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/screen/SignupScreen.kt
  presentation/src/main/java/com/kin/presentation/viewmodel/SignupViewModel.kt
Labels: 1️⃣ Priority: High

#48 🔀 :: (#39) signup logic
  data/src/main/java/com/kin/data/util/LoginInterceptor.kt
  presentation/src/main/java/com/kin/presentation/ui/change_password/screen/ChangePasswordScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/check_email/screen/CheckEmailScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/component/back_page/BackPage.kt
  presentation/src/main/java/com/kin/presentation/ui/component/navigation/NavigationGraph.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/screen/CreateGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/screen/DetailGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_management/screen/GroupManagementScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/screen/GroupSettingScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/screen/GroupTodoScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/join_private_group/screen/JoinPrivateGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/screen/NewGroupDescriptionScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/SignUpActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/screen/SignupScreen.kt
  presentation/src/main/java/com/kin/presentation/viewmodel/SignupViewModel.kt
Labels: 1️⃣ Priority: High

#50 🔀 :: (#37) group list logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kin/forest_android/module/NetworkModule.kt
  app/src/main/java/com/kin/forest_android/module/RemoteDataSourceModule.kt
  app/src/main/java/com/kin/forest_android/module/RepositoryModule.kt
  data/src/main/java/com/kin/data/remote/api/group_list/GroupListAPI.kt
  data/src/main/java/com/kin/data/remote/datasource/group_list/GroupListDataSource.kt
  data/src/main/java/com/kin/data/remote/datasource/group_list/GroupListDataSourceImpl.kt
  data/src/main/java/com/kin/data/remote/dto/group_list/response/GroupListResponse.kt
  data/src/main/java/com/kin/data/repository/GroupListRepositoryImpl.kt
  data/src/main/java/com/kin/data/util/Interceptor.kt
  domain/src/main/java/com/kin/domain/model/group_list/response/GroupListResponseModel.kt
  domain/src/main/java/com/kin/domain/repository/GroupListRepository.kt
  domain/src/main/java/com/kin/domain/usecase/group_list/GetGroupListUseCase.kt
  presentation/src/main/java/com/kin/presentation/ui/change_password/screen/ChangePasswordScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/check_email/screen/CheckEmailScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/component/back_page/BackPage.kt
  presentation/src/main/java/com/kin/presentation/ui/component/navigation/NavigationGraph.kt
  presentation/src/main/java/com/kin/presentation/ui/create_group/screen/CreateGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/deatil_group/screen/DetailGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/component/GroupList.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/component/GroupListTitle.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/item/GroupItemList.kt
  presentation/src/main/java/com/kin/presentation/ui/group_list/screen/GroupListScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_management/screen/GroupManagementScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_setting/screen/GroupSettingScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/component/private_todo/check_item/PrivateCheckItem.kt
  presentation/src/main/java/com/kin/presentation/ui/group_todo/screen/GroupTodoScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/home/MainActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/home/component/GroupList.kt
  presentation/src/main/java/com/kin/presentation/ui/home/item/GroupItemList.kt
  presentation/src/main/java/com/kin/presentation/ui/home/screen/HomeScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/join_private_group/screen/JoinPrivateGroupScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/EmailTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/login/component/PasswordTextField.kt
  presentation/src/main/java/com/kin/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/new_group_description/screen/NewGroupDescriptionScreen.kt
  presentation/src/main/java/com/kin/presentation/ui/signup/screen/SignupScreen.kt
  presentation/src/main/java/com/kin/presentation/viewmodel/GroupListViewModel.kt
  presentation/src/main/res/drawable/group.xml
  presentation/src/main/res/drawable/mygroup.xml
  presentation/src/main/res/drawable/mypage.xml
  presentation/src/main/res/drawable/not_group.xml
  presentation/src/main/res/drawable/not_mygroup.xml
  presentation/src/main/res/drawable/not_mypage.xml
Labels: 1️⃣ Priority: High, ✨ Type: Feature, 📬 Type: API
